### ISSUE TITLE
Decentraleyes doesn't work, crashes

### ISSUE THREAD

**Issue by ds6** [ungoogled-software/ungoogled-chromium-android#34]
https://decentraleyes.org/test does not pass, and tapping the gear icon on `popup.html` crashes.
Logcat:
```
[10-12 13:48:02.769 31528:31528 E/chromium]
[ERROR:extension_tab_util.cc(880)] Cannot open new tab here

[10-12 13:48:02.857 7235:11422 I/ndroid.systemu]
Explicit concurrent copying GC freed 6076(422KB) AllocSpace objects, 1(20KB) LOS objects, 47% free, 26MB/50MB, paused 128us total 337.397ms

[10-12 13:48:03.082 31528:31528 F/libc]
Fatal signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xc7eb3d74 in tid 31528 (tensions.stable), pid 31528 (tensions.stable)

[10-12 13:48:03.214 8550:8550 I/crash_dump32]
obtaining output fd from tombstoned, type: kDebuggerdTombstone

[10-12 13:48:03.218 1916:1916 I//system/bin/tombstoned]
received crash request for pid 31528

[10-12 13:48:03.220 8550:8550 I/crash_dump32]
performing dump of process 31528 (target tid = 31528)

[10-12 13:48:03.243 8550:8550 F/DEBUG]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

[10-12 13:48:03.244 8550:8550 F/DEBUG]
LineageOS Version: '16.0-20200128-NIGHTLY-pioneer'

[10-12 13:48:03.244 8550:8550 F/DEBUG]
Build fingerprint: 'Sony/H3113/H3113:8.0.0/50.1.A.4.76/2209478692:user/release-keys'

[10-12 13:48:03.244 8550:8550 F/DEBUG]
Revision: '0'

[10-12 13:48:03.244 8550:8550 F/DEBUG]
ABI: 'arm'

[10-12 13:48:03.244 8550:8550 F/DEBUG]
pid: 31528, tid: 31528, name: tensions.stable  >>> org.ungoogled.chromium.extensions.stable <<<

[10-12 13:48:03.244 8550:8550 F/DEBUG]
signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xc7eb3d74

[10-12 13:48:03.244 8550:8550 F/DEBUG]
    r0  cd308e2c  r1  00000001  r2  00000002  r3  00000000

[10-12 13:48:03.244 8550:8550 F/DEBUG]
    r4  cd308e10  r5  00000000  r6  ff8bc1a4  r7  00000000

[10-12 13:48:03.244 8550:8550 F/DEBUG]
    r8  c914d625  r9  ff8bc1a8  r10 cd3097c0  r11 c91abd35

[10-12 13:48:03.244 8550:8550 F/DEBUG]
    ip  c7eb3d75  sp  ff8bc178  lr  ca34fc2d  pc  c7eb3d74

[10-12 13:48:03.488 8550:8550 F/DEBUG]

backtrace:

[10-12 13:48:03.488 8550:8550 F/DEBUG]
    #00 pc 00c08d74  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.488 8550:8550 F/DEBUG]
    #01 pc 030a4c29  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.488 8550:8550 F/DEBUG]
    #02 pc 0309e2ad  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.488 8550:8550 F/DEBUG]
    #03 pc 0306baf9  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.488 8550:8550 F/DEBUG]
    #04 pc 03070143  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.488 8550:8550 F/DEBUG]
    #05 pc 02fe8985  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.488 8550:8550 F/DEBUG]
    #06 pc 02e561c9  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.488 8550:8550 F/DEBUG]
    #07 pc 0159ed6d  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #08 pc 0151a6b9  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #09 pc 0151bd0f  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #10 pc 0151b65b  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #11 pc 01529e41  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #12 pc 02e3c3fd  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #13 pc 01443bdb  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #14 pc 012e6ac1  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #15 pc 020a0a89  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #16 pc 01ed152d  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #17 pc 01edc3df  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #18 pc 01edc9c5  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #19 pc 01f00309  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #20 pc 01f00175  /data/app/org.ungoogled.chromium.extensions.stable-FlBRkExooNwEXLUJdCud6g==/base.apk (offset 0x1118000)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #21 pc 0000f235  /system/lib/libutils.so (android::Looper::pollInner(int)+632)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #22 pc 0000ef3f  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+26)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #23 pc 000b7d13  /system/lib/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long long, int)+24)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #24 pc 00390215  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.media.MediaExtractor.seekTo [DEDUPED]+92)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #25 pc 008ffd5d  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.os.MessageQueue.next+204)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #26 pc 008fdcd7  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.os.Looper.loop+590)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #27 pc 00743649  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.app.ActivityThread.main+664)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #28 pc 0040d575  /system/lib/libart.so (offset 0x344000) (art_quick_invoke_stub_internal+68)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #29 pc 003e6cd3  /system/lib/libart.so (offset 0x344000) (art_quick_invoke_static_stub+222)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #30 pc 000a1027  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #31 pc 00347b05  /system/lib/libart.so (offset 0x305000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #32 pc 00348f55  /system/lib/libart.so (offset 0x305000) (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+1024)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #33 pc 002fb105  /system/lib/libart.so (offset 0x2b0000) (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+40)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #34 pc 0010c26f  /system/framework/arm/boot.oat (offset 0x106000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+110)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #35 pc 009f76d3  /system/framework/arm/boot-framework.oat (offset 0x383000) (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+114)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #36 pc 009fd76d  /system/framework/arm/boot-framework.oat (offset 0x383000) (com.android.internal.os.ZygoteInit.main+2884)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #37 pc 0040d575  /system/lib/libart.so (offset 0x344000) (art_quick_invoke_stub_internal+68)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #38 pc 003e6cd3  /system/lib/libart.so (offset 0x344000) (art_quick_invoke_static_stub+222)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #39 pc 000a1027  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #40 pc 00347b05  /system/lib/libart.so (offset 0x305000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #41 pc 0034792f  /system/lib/libart.so (offset 0x305000) (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+310)

[10-12 13:48:03.489 8550:8550 F/DEBUG]
    #42 pc 0028eb55  /system/lib/libart.so (offset 0x1a3000) (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+444)

[10-12 13:48:03.490 8550:8550 F/DEBUG]
    #43 pc 0006cbcb  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+30)

[10-12 13:48:03.490 8550:8550 F/DEBUG]
    #44 pc 0006ee23  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+458)

[10-12 13:48:03.490 8550:8550 F/DEBUG]
    #45 pc 00001989  /system/bin/app_process32 (main+728)

[10-12 13:48:03.490 8550:8550 F/DEBUG]
    #46 pc 0008bd6d  /system/lib/libc.so (__libc_init+48)

[10-12 13:48:03.490 8550:8550 F/DEBUG]
    #47 pc 0000166f  /system/bin/app_process32 (_start_main+38)

[10-12 13:48:03.490 8550:8550 F/DEBUG]
    #48 pc 00000306  <anonymous:f4cd0000>

[10-12 13:48:04.031 1916:1916 E//system/bin/tombstoned]
Tombstone written to: /data/tombstones/tombstone_44

[10-12 13:48:04.042 3266:8553 W/ActivityManager]
  Force finishing activity org.ungoogled.chromium.extensions.stable/com.google.android.apps.chrome.Main

[10-12 13:48:04.043 3266:3289 I/BootReceiver]
Copying /data/tombstones/tombstone_44 to DropBox (SYSTEM_TOMBSTONE)

[10-12 13:48:04.081 3266:8553 W/ActivityManager]
Exception thrown during pause
android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:1129)
	at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:1777)
	at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:129)
	at com.android.server.am.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
	at com.android.server.am.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:69)
	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1460)
	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3749)
	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3691)
	at com.android.server.am.ActivityStack.finishTopCrashedActivityLocked(ActivityStack.java:3574)
	at com.android.server.am.ActivityStackSupervisor.finishTopCrashedActivitiesLocked(ActivityStackSupervisor.java:2262)
	at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:748)
	at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:580)
	at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:447)
	at com.android.server.am.AppErrors.crashApplication(AppErrors.java:392)
	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:15598)
	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:85)

[10-12 13:48:04.100 3266:3368 W/InputDispatcher]
channel '994107 org.ungoogled.chromium.extensions.stable/com.google.android.apps.chrome.Main (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

[10-12 13:48:04.100 3266:3368 E/InputDispatcher]
channel '994107 org.ungoogled.chromium.extensions.stable/com.google.android.apps.chrome.Main (server)' ~ Channel is unrecoverably broken and will be disposed!
```

LineageOS 16 on Sony XA2
F-Droid build 85.0.4183.121

**Comment by wchen342** [comment]
Fixed with 83576a6.
